const USERS_LIST = [
  {
    id: "1",
    firstName: "foulen",
    lastName: "ben foulen",
    login: "foulen",
    password: "123",
    contact: {
      email: "foulen@gmail.com",
      phoneNumber: "58485001",
    },
    group: "admin",
  },
  {
    id: "2",
    firstName: "foulen2",
    lastName: "ben foulen",
    login: "foulen",
    password: "123",
    contact: {
      email: "foulen@gmail.com",
      phoneNumber: "58485001",
    },
    group: "archivist",
  },
  {
    id: "3",
    firstName: "foulen3",
    lastName: "ben foulen",
    login: "foulen",
    password: "123",
    contact: {
      email: "foulen@gmail.com",
      phoneNumber: "58485001",
    },
    group: "rh",
  },
  {
    id: "4",
    firstName: "foulen4",
    lastName: "ben foulen",
    login: "foulen",
    password: "123",
    contact: {
      email: "foulen@gmail.com",
      phoneNumber: "58485001",
    },
    group: "archivist",
  },
  {
    id: "5",
    firstName: "foulen5",
    lastName: "ben foulen",
    login: "foulen",
    password: "123",
    contact: {
      email: "foulen@gmail.com",
      phoneNumber: "58485001",
    },
    group: "rh",
  },
  {
    id: "6",
    firstName: "foulen6",
    lastName: "ben foulen",
    login: "foulen",
    password: "123",
    contact: {
      email: "foulen@gmail.com",
      phoneNumber: "58485001",
    },
    group: "archivist",
  },
  {
    id: "7",
    firstName: "foulen7",
    lastName: "ben foulen",
    login: "foulen",
    password: "123",
    contact: {
      email: "foulen@gmail.com",
      phoneNumber: "58485001",
    },
    group: "rh",
  },
  {
    id: "8",
    firstName: "foulen8",
    lastName: "ben foulen",
    login: "foulen",
    password: "123",
    contact: {
      email: "foulen@gmail.com",
      phoneNumber: "58485001",
    },
    group: "rh",
  },
  {
    id: "9",
    firstName: "foulen9",
    lastName: "ben foulen",
    login: "foulen",
    password: "123",
    contact: {
      email: "foulen@gmail.com",
      phoneNumber: "58485001",
    },
    group: "rh",
  },
  {
    id: "10",
    firstName: "foulen9",
    lastName: "ben foulen",
    login: "foulen",
    password: "123",
    contact: {
      email: "foulen@gmail.com",
      phoneNumber: "58485001",
    },
    group: "rh",
  },
  {
    id: "11",
    firstName: "foulen9",
    lastName: "ben foulen",
    login: "foulen",
    password: "123",
    contact: {
      email: "foulen@gmail.com",
      phoneNumber: "58485001",
    },
    group: "rh",
  },
];

export default USERS_LIST;
